// Code generated by protoc-gen-go. DO NOT EDIT.
// source: updatecheck.proto

/*
Package updatecheck is a generated protocol buffer package.

It is generated from these files:
	updatecheck.proto

It has these top-level messages:
	UpdateCheckRequest
	UpdateCheckResponse
*/
package updatecheck

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OSType int32

const (
	OSType_IOS     OSType = 0
	OSType_ANDROID OSType = 1
)

var OSType_name = map[int32]string{
	0: "IOS",
	1: "ANDROID",
}
var OSType_value = map[string]int32{
	"IOS":     0,
	"ANDROID": 1,
}

func (x OSType) String() string {
	return proto.EnumName(OSType_name, int32(x))
}
func (OSType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ProductType int32

const (
	ProductType_FITAPP     ProductType = 0
	ProductType_TRAINERAPP ProductType = 1
)

var ProductType_name = map[int32]string{
	0: "FITAPP",
	1: "TRAINERAPP",
}
var ProductType_value = map[string]int32{
	"FITAPP":     0,
	"TRAINERAPP": 1,
}

func (x ProductType) String() string {
	return proto.EnumName(ProductType_name, int32(x))
}
func (ProductType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ResponseAction int32

const (
	ResponseAction_NONE   ResponseAction = 0
	ResponseAction_ADVICE ResponseAction = 1
	ResponseAction_FORCE  ResponseAction = 2
)

var ResponseAction_name = map[int32]string{
	0: "NONE",
	1: "ADVICE",
	2: "FORCE",
}
var ResponseAction_value = map[string]int32{
	"NONE":   0,
	"ADVICE": 1,
	"FORCE":  2,
}

func (x ResponseAction) String() string {
	return proto.EnumName(ResponseAction_name, int32(x))
}
func (ResponseAction) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type UpdateCheckRequest struct {
	OS             OSType      `protobuf:"varint,1,opt,name=OS,json=oS,enum=OSType" json:"OS,omitempty"`
	OSVersion      string      `protobuf:"bytes,2,opt,name=OSVersion,json=oSVersion" json:"OSVersion,omitempty"`
	Product        ProductType `protobuf:"varint,3,opt,name=Product,json=product,enum=ProductType" json:"Product,omitempty"`
	ProductVersion string      `protobuf:"bytes,4,opt,name=ProductVersion,json=productVersion" json:"ProductVersion,omitempty"`
}

func (m *UpdateCheckRequest) Reset()                    { *m = UpdateCheckRequest{} }
func (m *UpdateCheckRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateCheckRequest) ProtoMessage()               {}
func (*UpdateCheckRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UpdateCheckRequest) GetOS() OSType {
	if m != nil {
		return m.OS
	}
	return OSType_IOS
}

func (m *UpdateCheckRequest) GetOSVersion() string {
	if m != nil {
		return m.OSVersion
	}
	return ""
}

func (m *UpdateCheckRequest) GetProduct() ProductType {
	if m != nil {
		return m.Product
	}
	return ProductType_FITAPP
}

func (m *UpdateCheckRequest) GetProductVersion() string {
	if m != nil {
		return m.ProductVersion
	}
	return ""
}

type UpdateCheckResponse struct {
	Action ResponseAction `protobuf:"varint,1,opt,name=action,enum=ResponseAction" json:"action,omitempty"`
}

func (m *UpdateCheckResponse) Reset()                    { *m = UpdateCheckResponse{} }
func (m *UpdateCheckResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateCheckResponse) ProtoMessage()               {}
func (*UpdateCheckResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UpdateCheckResponse) GetAction() ResponseAction {
	if m != nil {
		return m.Action
	}
	return ResponseAction_NONE
}

func init() {
	proto.RegisterType((*UpdateCheckRequest)(nil), "UpdateCheckRequest")
	proto.RegisterType((*UpdateCheckResponse)(nil), "UpdateCheckResponse")
	proto.RegisterEnum("OSType", OSType_name, OSType_value)
	proto.RegisterEnum("ProductType", ProductType_name, ProductType_value)
	proto.RegisterEnum("ResponseAction", ResponseAction_name, ResponseAction_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for UpdateCheckService service

type UpdateCheckServiceClient interface {
	Query(ctx context.Context, in *UpdateCheckRequest, opts ...grpc.CallOption) (*UpdateCheckResponse, error)
}

type updateCheckServiceClient struct {
	cc *grpc.ClientConn
}

func NewUpdateCheckServiceClient(cc *grpc.ClientConn) UpdateCheckServiceClient {
	return &updateCheckServiceClient{cc}
}

func (c *updateCheckServiceClient) Query(ctx context.Context, in *UpdateCheckRequest, opts ...grpc.CallOption) (*UpdateCheckResponse, error) {
	out := new(UpdateCheckResponse)
	err := grpc.Invoke(ctx, "/UpdateCheckService/Query", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UpdateCheckService service

type UpdateCheckServiceServer interface {
	Query(context.Context, *UpdateCheckRequest) (*UpdateCheckResponse, error)
}

func RegisterUpdateCheckServiceServer(s *grpc.Server, srv UpdateCheckServiceServer) {
	s.RegisterService(&_UpdateCheckService_serviceDesc, srv)
}

func _UpdateCheckService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateCheckServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UpdateCheckService/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateCheckServiceServer).Query(ctx, req.(*UpdateCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UpdateCheckService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "UpdateCheckService",
	HandlerType: (*UpdateCheckServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _UpdateCheckService_Query_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "updatecheck.proto",
}

func init() { proto.RegisterFile("updatecheck.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 306 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x5f, 0x4b, 0x02, 0x41,
	0x14, 0xc5, 0x77, 0x56, 0xdd, 0x6d, 0xaf, 0xb1, 0x6d, 0xd7, 0x20, 0x89, 0x08, 0xf1, 0xc1, 0xcc,
	0x87, 0x81, 0xac, 0xe7, 0x60, 0xd1, 0x15, 0xb6, 0x87, 0x1d, 0x9b, 0x31, 0xdf, 0x6d, 0x1d, 0x48,
	0x02, 0x67, 0xda, 0x3f, 0x81, 0x9f, 0xa5, 0x2f, 0x1b, 0x3b, 0x2a, 0xb4, 0xd4, 0xe3, 0xf9, 0x5d,
	0xce, 0x99, 0x33, 0xf7, 0xc2, 0x79, 0xa9, 0xd7, 0xab, 0x42, 0xa6, 0xef, 0x32, 0xfd, 0xa0, 0x3a,
	0x53, 0x85, 0xea, 0x7f, 0x13, 0xc0, 0x57, 0x43, 0x27, 0x15, 0xe5, 0xf2, 0xb3, 0x94, 0x79, 0x81,
	0x97, 0x60, 0x33, 0xd1, 0x25, 0x3d, 0x32, 0xf4, 0xc7, 0x2e, 0x65, 0x62, 0xb1, 0xd3, 0x92, 0xdb,
	0x4a, 0xe0, 0x35, 0x78, 0x4c, 0x2c, 0x65, 0x96, 0x6f, 0xd4, 0xb6, 0x6b, 0xf7, 0xc8, 0xd0, 0xe3,
	0x9e, 0x3a, 0x02, 0x1c, 0x80, 0x3b, 0xcf, 0xd4, 0xba, 0x4c, 0x8b, 0x6e, 0xc3, 0x78, 0x4f, 0xe9,
	0x41, 0x9b, 0x00, 0x57, 0xef, 0x05, 0x0e, 0xc0, 0x3f, 0xf0, 0x63, 0x54, 0xd3, 0x44, 0xf9, 0xba,
	0x46, 0xfb, 0x4f, 0xd0, 0xa9, 0x95, 0xcb, 0xb5, 0xda, 0xe6, 0x12, 0x6f, 0xc1, 0x59, 0xa5, 0x45,
	0x65, 0xdb, 0x37, 0x3c, 0xa3, 0xc7, 0x51, 0x68, 0x30, 0x3f, 0x8c, 0x47, 0x37, 0xe0, 0xec, 0xbb,
	0xa3, 0x0b, 0x8d, 0x98, 0x89, 0xc0, 0xc2, 0x36, 0xb8, 0x61, 0x32, 0xe5, 0x2c, 0x9e, 0x06, 0x64,
	0x74, 0x07, 0xed, 0x5f, 0xfd, 0x10, 0xc0, 0x99, 0xc5, 0x8b, 0x70, 0x3e, 0x0f, 0x2c, 0xf4, 0x01,
	0x16, 0x3c, 0x8c, 0x93, 0x88, 0x57, 0x9a, 0x8c, 0xee, 0xc1, 0xaf, 0x3f, 0x82, 0x27, 0xd0, 0x4c,
	0x58, 0x12, 0x05, 0x56, 0xe5, 0x0b, 0xa7, 0xcb, 0x78, 0x12, 0x05, 0x04, 0x3d, 0x68, 0xcd, 0x18,
	0x9f, 0x44, 0x81, 0x3d, 0x7e, 0xae, 0xad, 0x56, 0xc8, 0xec, 0x6b, 0x93, 0x4a, 0x7c, 0x84, 0xd6,
	0x4b, 0x29, 0xb3, 0x1d, 0x76, 0xe8, 0xdf, 0xc5, 0x5f, 0x5d, 0xd0, 0x7f, 0x3e, 0xdc, 0xb7, 0xde,
	0x1c, 0x73, 0xae, 0x87, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa6, 0xf8, 0x58, 0x37, 0xc3, 0x01,
	0x00, 0x00,
}
